trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
  BuildConfiguration: 'Release'

steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 4.9.1'
    inputs:
      versionSpec: '4.9.1'

  - task: NuGetCommand@2
    displayName: 'Restore Public NuGet Packages'
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: 'Build Models Library'
    inputs:
      command: 'build'
      projects: 'src/Dfe.Spi.Models/Dfe.Spi.Models/Dfe.Spi.Models.csproj'
      arguments: '--configuration $(BuildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Pack Models Library'
    inputs:
      command: 'pack'
      packagesToPack: 'src/Dfe.Spi.Models/Dfe.Spi.Models/Dfe.Spi.Models.csproj'
      nobuild: true
      versioningScheme: 'off'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'